# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

Distance <- function(x, center, cov) {
    .Call(`_KemansToGmm_Distance`, x, center, cov)
}

sampledensity <- function(x, mean, sigma) {
    .Call(`_KemansToGmm_sampledensity`, x, mean, sigma)
}

iteration_gmm <- function(g, n, m, samp) {
    .Call(`_KemansToGmm_iteration_gmm`, g, n, m, samp)
}

